package estructurasdedatos;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class VistaGrafo extends javax.swing.JPanel {

    /**
     * Creates new form VistaArbolRN
     */
    private Grafo grafo;

    public VistaGrafo() {
        grafo = new Grafo();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaMostrarDespuesEliminarNodo1 = new javax.swing.JTextArea();
        btnEnviar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDatosEntrada = new javax.swing.JTextField();
        btnDesconectar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMostrarNodos = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();
        txtNodosDesconectar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaMostrarNodosDespuesDesconectar = new javax.swing.JTextArea();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNodoEliminar = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaMostrarDespuesEliminarNodo = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtConexionesNodos = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrese un valor para eliminar del Arbol AVL:");

        textAreaMostrarDespuesEliminarNodo1.setColumns(20);
        textAreaMostrarDespuesEliminarNodo1.setRows(5);
        jScrollPane3.setViewportView(textAreaMostrarDespuesEliminarNodo1);

        btnEnviar1.setBackground(new java.awt.Color(0, 204, 102));
        btnEnviar1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEnviar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar1.setText("Enviar");
        btnEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Grafo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese los nodos para el grafo (separados por espacios):");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtDatosEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatosEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(txtDatosEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 510, -1));

        btnDesconectar.setBackground(new java.awt.Color(0, 204, 102));
        btnDesconectar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnDesconectar.setForeground(new java.awt.Color(255, 255, 255));
        btnDesconectar.setText("Desconectar nodos");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, -1));

        txtAreaMostrarNodos.setColumns(20);
        txtAreaMostrarNodos.setRows(5);
        jScrollPane1.setViewportView(txtAreaMostrarNodos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 510, 130));

        btnRegresar.setBackground(new java.awt.Color(255, 51, 51));
        btnRegresar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, -1, -1));

        txtNodosDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNodosDesconectarActionPerformed(evt);
            }
        });
        jPanel1.add(txtNodosDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 90, 190, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Conexiones del grafo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        textAreaMostrarNodosDespuesDesconectar.setColumns(20);
        textAreaMostrarNodosDespuesDesconectar.setRows(5);
        jScrollPane2.setViewportView(textAreaMostrarNodosDespuesDesconectar);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 530, 130));

        btnEliminar.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese las conexiones para el grafo en el formato 'nodo1 nodo2' (una por linea, ingrese 'fin' para terminar):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Conexiones en el grafo despues de desconectar los nodos:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 8)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ingrese el nodo origen y destino a desconectar en el formato 'nodo1 nodo2':");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, 20));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ingrese un valor para eliminar del Arbol AVL:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, -1));

        txtNodoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNodoEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(txtNodoEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, 200, -1));

        textAreaMostrarDespuesEliminarNodo.setColumns(20);
        textAreaMostrarDespuesEliminarNodo.setRows(5);
        jScrollPane4.setViewportView(textAreaMostrarDespuesEliminarNodo);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 520, 130));

        txtConexionesNodos.setColumns(20);
        txtConexionesNodos.setRows(5);
        jScrollPane5.setViewportView(txtConexionesNodos);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 510, 110));

        btnEnviar.setBackground(new java.awt.Color(0, 204, 102));
        btnEnviar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatosEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatosEntradaActionPerformed

    }//GEN-LAST:event_txtDatosEntradaActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        try {
            String nodosDesconectar = txtNodosDesconectar.getText().trim();
            String[] nodos = nodosDesconectar.split(" ");
            if (nodos.length == 2) {
                int nodo1 = Integer.parseInt(nodos[0]);
                int nodo2 = Integer.parseInt(nodos[1]);
                grafo.desconectar(nodo1, nodo2);
                textAreaMostrarNodosDespuesDesconectar.setText("Conexiones en el grafo después de desconectar los nodos " + nodo1 + " y " + nodo2 + ":\n" + grafo.obtenerConexiones());
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese dos nodos válidos para desconectar.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese números válidos para los nodos.");
        }
    }//GEN-LAST:event_btnDesconectarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // Cerrar el JFrame actual
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();

        // Crear y mostrar el JFrame principal
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame("Vista Principal");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.getContentPane().add(new VistaPrincipal());
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtNodosDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNodosDesconectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNodosDesconectarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            int nodoEliminar = Integer.parseInt(txtNodoEliminar.getText().trim());
            grafo.eliminar(nodoEliminar);
            textAreaMostrarDespuesEliminarNodo.setText("Conexiones en el grafo después de eliminar el nodo " + nodoEliminar + ":\n" + grafo.obtenerConexiones());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido para eliminar.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNodoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNodoEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNodoEliminarActionPerformed

    private void btnEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar1ActionPerformed

    }//GEN-LAST:event_btnEnviar1ActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String datosEntrada = txtDatosEntrada.getText();
        String[] nodos = datosEntrada.split(" ");
        for (String nodo : nodos) {
            try {
                int valor = Integer.parseInt(nodo.trim());
                grafo.insertar(valor);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese solo números separados por espacios.");
            }
        }

        String conexiones = txtConexionesNodos.getText();
        String[] conexionesLineas = conexiones.split("\n");
        for (String linea : conexionesLineas) {
            if (linea.trim().equalsIgnoreCase("fin")) {
                break;
            }
            String[] nodosConectados = linea.split(" ");
            if (nodosConectados.length == 2) {
                try {
                    int nodo1 = Integer.parseInt(nodosConectados[0].trim());
                    int nodo2 = Integer.parseInt(nodosConectados[1].trim());
                    grafo.conectar(nodo1, nodo2);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Ingrese conexiones válidas en el formato 'nodo1 nodo2'.");
                }
            }
        }

        txtAreaMostrarNodos.setText("Conexiones en el grafo:\n" + grafo.obtenerConexiones());
    }//GEN-LAST:event_btnEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnEnviar1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea textAreaMostrarDespuesEliminarNodo;
    private javax.swing.JTextArea textAreaMostrarDespuesEliminarNodo1;
    private javax.swing.JTextArea textAreaMostrarNodosDespuesDesconectar;
    private javax.swing.JTextArea txtAreaMostrarNodos;
    private javax.swing.JTextArea txtConexionesNodos;
    private javax.swing.JTextField txtDatosEntrada;
    private javax.swing.JTextField txtNodoEliminar;
    private javax.swing.JTextField txtNodosDesconectar;
    // End of variables declaration//GEN-END:variables
}
